<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>XerToCsvConverter</RootNamespace>
    <Version>2.6.0</Version>
    <AssemblyVersion>2.6.0.0</AssemblyVersion>
    <FileVersion>2.6.0.0</FileVersion>
  </PropertyGroup>
</Project>
